# Generated by Django 3.2.7 on 2021-09-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Provide',
            new_name='Provider',
        ),
    ]
